name: 02 - Env and Secrets
on:
  workflow_dispatch:
jobs:
  env_and_secrets:
    runs-on: ubuntu-latest
    env:
      GLOBAL_GREETING: "Hello from job env"
    steps:
      - name: Step-level env
        env:
          STEP_GREETING: "Hello from step env"
        run: |
          echo "$GLOBAL_GREETING"
          echo "$STEP_GREETING"
      - name: Demonstrate secret masking
        # Set a repo secret named DEMO_SECRET to see masking (*** in logs)
        run: |
          echo "Secret masked in logs: ${{ secrets.DEMO_SECRET }}"
      - name: Create a step output
        id: make_output
        run: echo "message=This came from a step output" >> $GITHUB_OUTPUT
      - name: Use the step output
        run: echo "We read: ${{ steps.make_output.outputs.message }}"
