name: 17 - Weekly Issue Summary
on:
  workflow_dispatch:
  schedule:
    - cron: '0 9 * * 1'  # Every Monday 09:00 UTC (adjust as desired)

permissions:
  issues: write
  contents: read
  models: read

jobs:
  create_weekly_summary:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install gh-models extension
        run: gh extension install https://github.com/github/gh-models
        env:
          GH_TOKEN: ${{ github.token }}

      - name: Get issues from the past week and summarize
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          LAST_WEEK=$(date -d "7 days ago" +"%Y-%m-%d")
          gh search issues "created:>$LAST_WEEK" --state=open --json title,body,url --repo ${{ github.repository }} > issues.json

          # Run model with a prompt file stored in repo
          cat issues.json | gh models run --file prompts/issue-summary.prompt.yml > summary.md

          ISSUE_TITLE="Issue Summary - $(date -d '7 days ago' '+%B %d') to $(date '+%B %d')"
          gh issue create --title "$ISSUE_TITLE" --label summary --body-file summary.md
